### ISSUE TITLE
When issuing a new subscription that overrides another one, we should freak out

### ISSUE THREAD

**Issue by davidjairala** [queue-bus/queue-bus#7]
For example, I made the following subscription in one place:

``` ruby
subscribe_queue :metrics_events, :clear_data, bus_event_type: 'heartbeat_minutes'
```

But I had already subscribed to `heartbeat_minutes` for `metrics_events` in another place:

``` ruby
subscribe_queue :metrics_events, :create_indexes, bus_event_type: 'heartbeat_minutes'
```

Which led to the new subscription not appearing in the subscription list.  This is understandable, but it's probably better if we raise an exception when running subscriptions instead of just overriding, for clarity.

**Comment by evantahler** [comment]
To clarify: are you suggesting that the application (IE: the queue-bus gem) check the collection of subscriptions before subscribing to ensure that each hash key is unique?   I can't think of a good way to do this in redis (or across apps), but safety within a single instance of the app seems OK to me!

**Comment by bleonard** [comment]
It wouldn't just be on subscribing, probably. every thread of the application will load the subscription in order to be ready to process them. The choke point seems to be `add` here: https://github.com/queue-bus/queue-bus/blob/cbf2fb4a74deb7a89149361855978af9f97effe5/lib/queue_bus/subscription_list.rb#L30

We could freak out if it was already there.
In all likelihood, it's a mistake if there is the same key twice and will lead to something not happening as expected.

**Comment by davidjairala** [comment]
@bleonard I can take a crack at this one if you haven't started already.  LMK.

**Comment by bleonard** [comment]
Sure thing. It's fun to get new names on the commiter page!
